# reference: https://github.com/marketplace/actions/github-events-to-feishu-bot-action

name: feishu bot

on:
  # branch_protection_rule:
  #   types: [created, deleted]
  check_run:
    types: [rerequested, completed]
  check_suite:
    types: [completed]
  # create:
  # delete:
  # deployment_status:
  # discussion:
  #   types: [created, edited, answered]
  # discussion_comment:
  #   types: [created, deleted]
  # fork:
  # gollum:
  # issues:
  #   types: [opened, edited, milestoned, pinned, reopened]
  # issue_comment:
  #   types: [created, deleted]
  # label:
  #   types: [created, deleted]
  # merge_group:
  #   types: [checks_requested]
  # milestone:
  #   types: [opened, deleted]
  # page_build:
  # project:
  #   types: [created, deleted, reopened]
  # project_card:
  #   types: [created, deleted]
  # project_column:
  #   types: [created, deleted]
  # public:
  pull_request:
    branches: ['main']
    types: [opened, reopened, closed]
  pull_request_review:
    types: [edited, dismissed, submitted]
  pull_request_review_comment:
    types: [created, edited, deleted]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches: ['main', 'master']
  # registry_package:
  #   types: [published]
  release:
    types: [published]
  status:
  watch:
    types: [started]
  # schedule:
  #   - cron: '30 2 * * *'

jobs:
  send-event:
    name: Webhook
    runs-on: ubuntu-latest
    steps:
      - uses: junka/feishu-bot-webhook-action@1.0.11
        with:
          webhook: ${{ secrets.FEISHU_BOT_WEBHOOK }}
          signkey: ${{ secrets.FEISHU_BOT_SIGNKEY }}
